// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoz1UypyauJTiiz8bQt-cr4ZNH1tRSNQ',
    appId: '1:644792580383:android:7d98bbfa9a8de0bfdfd82a',
    messagingSenderId: '644792580383',
    projectId: 'campbelldecor-c2d1f',
    storageBucket: 'campbelldecor-c2d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwEPj8fElflD_zr0017RagfJpZ5EY5KM',
    appId: '1:644792580383:ios:5680b323e45d619fdfd82a',
    messagingSenderId: '644792580383',
    projectId: 'campbelldecor-c2d1f',
    storageBucket: 'campbelldecor-c2d1f.appspot.com',
    iosClientId: '644792580383-opm935pes939uhpfcq935jl2skmkvmtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.campbelldecor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwEPj8fElflD_zr0017RagfJpZ5EY5KM',
    appId: '1:644792580383:ios:1dba57a2090098d3dfd82a',
    messagingSenderId: '644792580383',
    projectId: 'campbelldecor-c2d1f',
    storageBucket: 'campbelldecor-c2d1f.appspot.com',
    iosClientId: '644792580383-cilou335jq123i89qahm8ptm84ns6m02.apps.googleusercontent.com',
    iosBundleId: 'com.example.campbelldecor.RunnerTests',
  );
}
